name: flutter_fit_utils
description: "A flutter package to easily manage data in and out of repositories. This package is the core of it's environement."
version: 4.0.0
homepage: https://pub.dev/packages/flutter_fit_utils
repository: https://github.com/Vaistudio-dev/flutter_fit_utils
issue_tracker: https://github.com/Vaistudio-dev/flutter_fit_utils/issues

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

topics:
  - models
  - repositories
  - services
  - extensions

environment:
  sdk: '>=3.3.3 <4.0.0'
