name: flutter_fit_utils
description: "A flutter package to easily manage data in and out of repositories. This package is the core of it's environement."
version: 1.0.0
repository: https://github.com/s0punk/flutter_fit_utils

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

topics:
  - firebase

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  cloud_firestore: ^4.17.3
  firebase_remote_config: ^4.4.5
  flutter:
    sdk: flutter
  intl: ^0.19.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
