name: flutter_fit_utils
description: "Set of utilities for Flutter apps."
version: 1.0.0
homepage:

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  cloud_firestore: ^4.17.3
  firebase_remote_config: ^4.4.5
  flutter:
    sdk: flutter
  intl: ^0.19.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter: