name: flutter_fit_utils
description: "A flutter package to easily manage data in and out of repositories. This package is the core of it's environement."
version: 2.3.2
homepage: https://pub.dev/packages/flutter_fit_utils
repository: https://github.com/s0punk/flutter_fit_utils
issue_tracker: https://github.com/s0punk/flutter_fit_utils/issues

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

topics:
  - models
  - repositories
  - services
  - extensions

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  cloud_firestore: ^5.6.2
  firebase_remote_config: ^5.3.1
  flutter:
    sdk: flutter
  hive: ^2.2.3
  intl: ^0.20.2
  shared_preferences: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
